name: Build and Test

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

permissions:
  contents: read
  actions: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 10.11.1
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      
      - run: pnpm install --frozen-lockfile
      
      - run: pnpm check
      
      - run: |
          if find . -type f \( -name "*.test.ts" -o -name "*.spec.ts" \) | grep -q .; then
            pnpm test
          else
            echo "⚠️ No test files found"
          fi
      
      - run: pnpm build
      
      - uses: actions/upload-artifact@v4
        with:
          name: build-files-${{ github.sha }}
          path: dist/
          retention-days: 7
