name: Publish Beta

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
    branches: [develop]

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  publish-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: pnpm/action-setup@v2
        with:
          version: 10.11.1
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
          cache: "pnpm"
      
      - run: pnpm install --frozen-lockfile
      
      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          name: build-files-${{ github.event.workflow_run.head_sha }}
          path: dist/
      
      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      
      - name: Create beta version
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          VERSION=$(node -p "require('./package.json').version")
          BETA="${VERSION}-beta.${TIMESTAMP}"
          npm version $BETA --no-git-tag-version
          echo "BETA_VERSION=$BETA" >> $GITHUB_ENV
      
      - name: Setup npm registry
        run: |
          echo "@vunky-himawan:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
      
      - name: Publish beta package
        run: pnpm publish --tag beta --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Commit and tag beta version
        run: |
          git add package.json
          git commit -m "chore: create beta version ${{ env.BETA_VERSION }}"
          git tag "v${{ env.BETA_VERSION }}"
          git push origin develop --tags
