name: Publish Production

on:
  push:
    branches: [main]

jobs:
  publish-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 10.11.1
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - uses: actions/download-artifact@v4
        with:
          name: build-files-${{ github.sha }}
          path: dist/
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - id: version-bump
        run: |
          COMMITS=$(git log --oneline $(git describe --tags --abbrev=0)..HEAD 2>/dev/null || git log --oneline)
          if echo "$COMMITS" | grep -qiE "BREAKING CHANGE|major:"; then
            echo "bump=major" >> $GITHUB_OUTPUT
          elif echo "$COMMITS" | grep -qiE "feat:|feature:|minor:"; then
            echo "bump=minor" >> $GITHUB_OUTPUT
          else
            echo "bump=patch" >> $GITHUB_OUTPUT
          fi
      - run: |
          npm version ${{ steps.version-bump.outputs.bump }} --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "PROD_VERSION=$VERSION" >> $GITHUB_ENV
      - run: |
          echo "@vunky-himawan:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
      - run: pnpm publish --tag latest --no-git-checks
      - run: |
          git add package.json
          git commit -m "chore: release version v${{ env.PROD_VERSION }}"
          git tag "v${{ env.PROD_VERSION }}"
          git push origin main --tags
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PROD_VERSION }}
          release_name: Release v${{ env.PROD_VERSION }}
          body: |
            ## Changes in v${{ env.PROD_VERSION }}
            Auto-generated release from main branch.
            ### Install
            ```bash
            pnpm add @vunky-himawan/zentara
            ```
